os:
  - linux
language: generic
sudo: required
dist: trusty
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
  - swift build
  - swift build -c release
after_script:
  - mkdir ./upload
  - cp .build/release/App ./upload
  - cd upload
  - git init
  - git config user.name "xjx00"
  - git config user.email "xjxyklwx@126.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:upload
