os:
  - linux
language: generic
sudo: required
dist: trusty
install:
  - sudo apt-get install clang libicu-dev
  - wget https://swift.org/builds/swift-3.1.1-release/ubuntu1610/swift-3.1.1-RELEASE/swift-3.1.1-RELEASE-ubuntu16.10.tar.gz
  - tar xzf swift-3.1.1-RELEASE-ubuntu16.10.tar.gz
  - export PATH=./swift-3.1.1-RELEASE-ubuntu16.10/usr/bin:"${PATH}"
script:
  - swift build
  - swift build -c release
after_script:
  - mkdir ./upload
  - mkdir ./upload/file
  - cp .build/release/App ./upload/file
  - cd upload
  - git init
  - git config user.name "xjx00"
  - git config user.email "xjxyklwx@126.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:upload
